<?php

namespace AppBundle\Repository;

/**
 * SinhvienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinhvienRepository extends \Doctrine\ORM\EntityRepository
{
}
